name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_REPO_NAME_OWNER: ${{ github.repository }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ISSUE_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  code-review:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'AI_CODE_REVIEW')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Print git diff
        run: git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} >> code-reviewer/diff.txt

      - name: Conduct Code Review
        run: cd code-reviewer && npm ci && npm run build && npm run review
